<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Docs\**" />
    <Compile Remove="Euchre.Console\**" />
    <Compile Remove="Euchre.Logic\**" />
    <Compile Remove="Euchre.Tests\**" />
    <EmbeddedResource Remove="Docs\**" />
    <EmbeddedResource Remove="Euchre.Console\**" />
    <EmbeddedResource Remove="Euchre.Logic\**" />
    <EmbeddedResource Remove="Euchre.Tests\**" />
    <None Remove="Docs\**" />
    <None Remove="Euchre.Console\**" />
    <None Remove="Euchre.Logic\**" />
    <None Remove="Euchre.Tests\**" />
    <Page Remove="Docs\**" />
    <Page Remove="Euchre.Console\**" />
    <Page Remove="Euchre.Logic\**" />
    <Page Remove="Euchre.Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="images\avatars\avatar1.png" />
    <None Remove="images\avatars\avatar10.png" />
    <None Remove="images\avatars\avatar11.png" />
    <None Remove="images\avatars\avatar12.png" />
    <None Remove="images\avatars\avatar13.png" />
    <None Remove="images\avatars\avatar14.png" />
    <None Remove="images\avatars\avatar15.png" />
    <None Remove="images\avatars\avatar16.png" />
    <None Remove="images\avatars\avatar17.png" />
    <None Remove="images\avatars\avatar18.png" />
    <None Remove="images\avatars\avatar19.png" />
    <None Remove="images\avatars\avatar2.png" />
    <None Remove="images\avatars\avatar20.png" />
    <None Remove="images\avatars\avatar21.png" />
    <None Remove="images\avatars\avatar22.png" />
    <None Remove="images\avatars\avatar23.png" />
    <None Remove="images\avatars\avatar24.png" />
    <None Remove="images\avatars\avatar3.png" />
    <None Remove="images\avatars\avatar4.png" />
    <None Remove="images\avatars\avatar5.png" />
    <None Remove="images\avatars\avatar6.png" />
    <None Remove="images\avatars\avatar7.png" />
    <None Remove="images\avatars\avatar8.png" />
    <None Remove="images\avatars\avatar9.png" />
    <None Remove="images\cardbacks\Cards Blue Card Back Rotated.png" />
    <None Remove="images\cardbacks\Cards Blue Card Back.png" />
    <None Remove="images\cardbacks\Cards Red Card Back Rotated.png" />
    <None Remove="images\cardbacks\Cards Red Card Back.png" />
    <None Remove="images\cardbacks\Grid Blue Card Back Rotated.png" />
    <None Remove="images\cardbacks\Grid Blue Card Back.png" />
    <None Remove="images\cardbacks\Grid Red Card Back Rotated.png" />
    <None Remove="images\cardbacks\Grid Red Card Back.png" />
    <None Remove="images\cardbacks\Simple Blue Card Back Rotated.png" />
    <None Remove="images\cardbacks\Simple Blue Card Back.png" />
    <None Remove="images\cardbacks\Simple Red Card Back Rotated.png" />
    <None Remove="images\cardbacks\Simple Red Card Back.png" />
    <None Remove="images\cardbacks\Suits Blue Card Back Rotated.png" />
    <None Remove="images\cardbacks\Suits Blue Card Back.png" />
    <None Remove="images\cardbacks\Suits Red Card Back Rotated.png" />
    <None Remove="images\cardbacks\Suits Red Card Back.png" />
    <None Remove="images\cards\ace of clubs disabled.png" />
    <None Remove="images\cards\ace of clubs rotated.png" />
    <None Remove="images\cards\ace of clubs.png" />
    <None Remove="images\cards\ace of diamonds disabled.png" />
    <None Remove="images\cards\ace of diamonds rotated.png" />
    <None Remove="images\cards\ace of diamonds.png" />
    <None Remove="images\cards\ace of hearts disabled.png" />
    <None Remove="images\cards\ace of hearts rotated.png" />
    <None Remove="images\cards\ace of hearts.png" />
    <None Remove="images\cards\ace of spades disabled.png" />
    <None Remove="images\cards\ace of spades rotated.png" />
    <None Remove="images\cards\ace of spades.png" />
    <None Remove="images\cards\eight of clubs disabled.png" />
    <None Remove="images\cards\eight of clubs rotated.png" />
    <None Remove="images\cards\eight of clubs.png" />
    <None Remove="images\cards\eight of diamonds disabled.png" />
    <None Remove="images\cards\eight of diamonds rotated.png" />
    <None Remove="images\cards\eight of diamonds.png" />
    <None Remove="images\cards\eight of hearts disabled.png" />
    <None Remove="images\cards\eight of hearts rotated.png" />
    <None Remove="images\cards\eight of hearts.png" />
    <None Remove="images\cards\eight of spades disabled.png" />
    <None Remove="images\cards\eight of spades rotated.png" />
    <None Remove="images\cards\eight of spades.png" />
    <None Remove="images\cards\Example.pdn" />
    <None Remove="images\cards\jack of clubs disabled.png" />
    <None Remove="images\cards\jack of clubs rotated.png" />
    <None Remove="images\cards\jack of clubs.png" />
    <None Remove="images\cards\jack of diamonds disabled.png" />
    <None Remove="images\cards\jack of diamonds rotated.png" />
    <None Remove="images\cards\jack of diamonds.png" />
    <None Remove="images\cards\jack of hearts disabled.png" />
    <None Remove="images\cards\jack of hearts rotated.png" />
    <None Remove="images\cards\jack of hearts.png" />
    <None Remove="images\cards\jack of spades disabled.png" />
    <None Remove="images\cards\jack of spades rotated.png" />
    <None Remove="images\cards\jack of spades.png" />
    <None Remove="images\cards\king of clubs disabled.png" />
    <None Remove="images\cards\king of clubs rotated.png" />
    <None Remove="images\cards\king of clubs.png" />
    <None Remove="images\cards\king of diamonds disabled.png" />
    <None Remove="images\cards\king of diamonds rotated.png" />
    <None Remove="images\cards\king of diamonds.png" />
    <None Remove="images\cards\king of hearts disabled.png" />
    <None Remove="images\cards\king of hearts rotated.png" />
    <None Remove="images\cards\king of hearts.png" />
    <None Remove="images\cards\king of spades disabled.png" />
    <None Remove="images\cards\king of spades rotated.png" />
    <None Remove="images\cards\king of spades.png" />
    <None Remove="images\cards\nine of clubs disabled.png" />
    <None Remove="images\cards\nine of clubs rotated.png" />
    <None Remove="images\cards\nine of clubs.png" />
    <None Remove="images\cards\nine of diamonds disabled.png" />
    <None Remove="images\cards\nine of diamonds rotated.png" />
    <None Remove="images\cards\nine of diamonds.png" />
    <None Remove="images\cards\nine of hearts disabled.png" />
    <None Remove="images\cards\nine of hearts rotated.png" />
    <None Remove="images\cards\nine of hearts.png" />
    <None Remove="images\cards\nine of spades disabled.png" />
    <None Remove="images\cards\nine of spades rotated.png" />
    <None Remove="images\cards\nine of spades.png" />
    <None Remove="images\cards\queen of clubs disabled.png" />
    <None Remove="images\cards\queen of clubs rotated.png" />
    <None Remove="images\cards\queen of clubs.png" />
    <None Remove="images\cards\queen of diamonds disabled.png" />
    <None Remove="images\cards\queen of diamonds rotated.png" />
    <None Remove="images\cards\queen of diamonds.png" />
    <None Remove="images\cards\queen of hearts disabled.png" />
    <None Remove="images\cards\queen of hearts rotated.png" />
    <None Remove="images\cards\queen of hearts.png" />
    <None Remove="images\cards\queen of spades disabled.png" />
    <None Remove="images\cards\queen of spades rotated.png" />
    <None Remove="images\cards\queen of spades.png" />
    <None Remove="images\cards\seven of clubs disabled.png" />
    <None Remove="images\cards\seven of clubs rotated.png" />
    <None Remove="images\cards\seven of clubs.png" />
    <None Remove="images\cards\seven of diamonds disabled.png" />
    <None Remove="images\cards\seven of diamonds rotated.png" />
    <None Remove="images\cards\seven of diamonds.png" />
    <None Remove="images\cards\seven of hearts disabled.png" />
    <None Remove="images\cards\seven of hearts rotated.png" />
    <None Remove="images\cards\seven of hearts.png" />
    <None Remove="images\cards\seven of spades disabled.png" />
    <None Remove="images\cards\seven of spades rotated.png" />
    <None Remove="images\cards\seven of spades.png" />
    <None Remove="images\cards\ten of clubs disabled.png" />
    <None Remove="images\cards\ten of clubs rotated.png" />
    <None Remove="images\cards\ten of clubs.png" />
    <None Remove="images\cards\ten of diamonds disabled.png" />
    <None Remove="images\cards\ten of diamonds rotated.png" />
    <None Remove="images\cards\ten of diamonds.png" />
    <None Remove="images\cards\ten of hearts disabled.png" />
    <None Remove="images\cards\ten of hearts rotated.png" />
    <None Remove="images\cards\ten of hearts.png" />
    <None Remove="images\cards\ten of spades disabled.png" />
    <None Remove="images\cards\ten of spades rotated.png" />
    <None Remove="images\cards\ten of spades.png" />
    <None Remove="images\icons\arrow left.png" />
    <None Remove="images\icons\arrow right.png" />
    <None Remove="images\icons\black.png" />
    <None Remove="images\icons\Cards-Play-128.png" />
    <None Remove="images\icons\Cards-Play-16.png" />
    <None Remove="images\icons\Cards-Play-32.png" />
    <None Remove="images\icons\Cards-Play-64.png" />
    <None Remove="images\icons\dealer.png" />
    <None Remove="images\icons\Exit-128.png" />
    <None Remove="images\icons\Exit-16.png" />
    <None Remove="images\icons\Exit-32.png" />
    <None Remove="images\icons\Exit-64.png" />
    <None Remove="images\icons\green.png" />
    <None Remove="images\icons\Help-128.png" />
    <None Remove="images\icons\Help-16.png" />
    <None Remove="images\icons\Help-32.png" />
    <None Remove="images\icons\Help-64.png" />
    <None Remove="images\icons\lead card indicator.png" />
    <None Remove="images\icons\Playing-Cards-128.ico" />
    <None Remove="images\icons\Playing-Cards-128.png" />
    <None Remove="images\icons\Playing-Cards-16.ico" />
    <None Remove="images\icons\Playing-Cards-16.png" />
    <None Remove="images\icons\Playing-Cards-32.ico" />
    <None Remove="images\icons\Playing-Cards-32.png" />
    <None Remove="images\icons\Playing-Cards-64.ico" />
    <None Remove="images\icons\Playing-Cards-64.png" />
    <None Remove="images\icons\red.png" />
    <None Remove="images\icons\Settings-01-128.png" />
    <None Remove="images\icons\Settings-01-16.png" />
    <None Remove="images\icons\Settings-01-32.png" />
    <None Remove="images\icons\Settings-01-64.png" />
    <None Remove="images\icons\Solo Original.pdn" />
    <None Remove="images\icons\Solo.ico" />
    <None Remove="images\icons\Solo.png" />
    <None Remove="images\icons\trick won indicator.png" />
    <None Remove="images\suits\Clubs.png" />
    <None Remove="images\suits\Diamonds.png" />
    <None Remove="images\suits\Hearts.png" />
    <None Remove="images\suits\Spades.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Euchre.Logic\Euchre.Logic.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CrazyCanuckCoder.Library.WPF">
      <HintPath>..\CrazyCanuckCoder\Library.WPF\bin\Debug\net8.0-windows\CrazyCanuckCoder.Library.WPF.dll</HintPath>
    </Reference>
    <Reference Include="CrazyCanuckCoder.Library.WPFControls">
      <HintPath>..\CrazyCanuckCoder\Library.WPFControls\bin\Debug\net8.0-windows\CrazyCanuckCoder.Library.WPFControls.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\avatars\avatar1.png" />
    <Resource Include="images\avatars\avatar10.png" />
    <Resource Include="images\avatars\avatar11.png" />
    <Resource Include="images\avatars\avatar12.png" />
    <Resource Include="images\avatars\avatar13.png" />
    <Resource Include="images\avatars\avatar14.png" />
    <Resource Include="images\avatars\avatar15.png" />
    <Resource Include="images\avatars\avatar16.png" />
    <Resource Include="images\avatars\avatar17.png" />
    <Resource Include="images\avatars\avatar18.png" />
    <Resource Include="images\avatars\avatar19.png" />
    <Resource Include="images\avatars\avatar2.png" />
    <Resource Include="images\avatars\avatar20.png" />
    <Resource Include="images\avatars\avatar21.png" />
    <Resource Include="images\avatars\avatar22.png" />
    <Resource Include="images\avatars\avatar23.png" />
    <Resource Include="images\avatars\avatar24.png" />
    <Resource Include="images\avatars\avatar3.png" />
    <Resource Include="images\avatars\avatar4.png" />
    <Resource Include="images\avatars\avatar5.png" />
    <Resource Include="images\avatars\avatar6.png" />
    <Resource Include="images\avatars\avatar7.png" />
    <Resource Include="images\avatars\avatar8.png" />
    <Resource Include="images\avatars\avatar9.png" />
    <Resource Include="images\cardbacks\Cards Blue Card Back Rotated.png" />
    <Resource Include="images\cardbacks\Cards Blue Card Back.png" />
    <Resource Include="images\cardbacks\Cards Red Card Back Rotated.png" />
    <Resource Include="images\cardbacks\Cards Red Card Back.png" />
    <Resource Include="images\cardbacks\Grid Blue Card Back Rotated.png" />
    <Resource Include="images\cardbacks\Grid Blue Card Back.png" />
    <Resource Include="images\cardbacks\Grid Red Card Back Rotated.png" />
    <Resource Include="images\cardbacks\Grid Red Card Back.png" />
    <Resource Include="images\cardbacks\Simple Blue Card Back Rotated.png" />
    <Resource Include="images\cardbacks\Simple Blue Card Back.png" />
    <Resource Include="images\cardbacks\Simple Red Card Back Rotated.png" />
    <Resource Include="images\cardbacks\Simple Red Card Back.png" />
    <Resource Include="images\cardbacks\Suits Blue Card Back Rotated.png" />
    <Resource Include="images\cardbacks\Suits Blue Card Back.png" />
    <Resource Include="images\cardbacks\Suits Red Card Back Rotated.png" />
    <Resource Include="images\cardbacks\Suits Red Card Back.png" />
    <Resource Include="images\cards\ace of clubs disabled.png" />
    <Resource Include="images\cards\ace of clubs rotated.png" />
    <Resource Include="images\cards\ace of clubs.png" />
    <Resource Include="images\cards\ace of diamonds disabled.png" />
    <Resource Include="images\cards\ace of diamonds rotated.png" />
    <Resource Include="images\cards\ace of diamonds.png" />
    <Resource Include="images\cards\ace of hearts disabled.png" />
    <Resource Include="images\cards\ace of hearts rotated.png" />
    <Resource Include="images\cards\ace of hearts.png" />
    <Resource Include="images\cards\ace of spades disabled.png" />
    <Resource Include="images\cards\ace of spades rotated.png" />
    <Resource Include="images\cards\ace of spades.png" />
    <Resource Include="images\cards\eight of clubs disabled.png" />
    <Resource Include="images\cards\eight of clubs rotated.png" />
    <Resource Include="images\cards\eight of clubs.png" />
    <Resource Include="images\cards\eight of diamonds disabled.png" />
    <Resource Include="images\cards\eight of diamonds rotated.png" />
    <Resource Include="images\cards\eight of diamonds.png" />
    <Resource Include="images\cards\eight of hearts disabled.png" />
    <Resource Include="images\cards\eight of hearts rotated.png" />
    <Resource Include="images\cards\eight of hearts.png" />
    <Resource Include="images\cards\eight of spades disabled.png" />
    <Resource Include="images\cards\eight of spades rotated.png" />
    <Resource Include="images\cards\eight of spades.png" />
    <Resource Include="images\cards\Example.pdn" />
    <Resource Include="images\cards\jack of clubs disabled.png" />
    <Resource Include="images\cards\jack of clubs rotated.png" />
    <Resource Include="images\cards\jack of clubs.png" />
    <Resource Include="images\cards\jack of diamonds disabled.png" />
    <Resource Include="images\cards\jack of diamonds rotated.png" />
    <Resource Include="images\cards\jack of diamonds.png" />
    <Resource Include="images\cards\jack of hearts disabled.png" />
    <Resource Include="images\cards\jack of hearts rotated.png" />
    <Resource Include="images\cards\jack of hearts.png" />
    <Resource Include="images\cards\jack of spades disabled.png" />
    <Resource Include="images\cards\jack of spades rotated.png" />
    <Resource Include="images\cards\jack of spades.png" />
    <Resource Include="images\cards\king of clubs disabled.png" />
    <Resource Include="images\cards\king of clubs rotated.png" />
    <Resource Include="images\cards\king of clubs.png" />
    <Resource Include="images\cards\king of diamonds disabled.png" />
    <Resource Include="images\cards\king of diamonds rotated.png" />
    <Resource Include="images\cards\king of diamonds.png" />
    <Resource Include="images\cards\king of hearts disabled.png" />
    <Resource Include="images\cards\king of hearts rotated.png" />
    <Resource Include="images\cards\king of hearts.png" />
    <Resource Include="images\cards\king of spades disabled.png" />
    <Resource Include="images\cards\king of spades rotated.png" />
    <Resource Include="images\cards\king of spades.png" />
    <Resource Include="images\cards\nine of clubs disabled.png" />
    <Resource Include="images\cards\nine of clubs rotated.png" />
    <Resource Include="images\cards\nine of clubs.png" />
    <Resource Include="images\cards\nine of diamonds disabled.png" />
    <Resource Include="images\cards\nine of diamonds rotated.png" />
    <Resource Include="images\cards\nine of diamonds.png" />
    <Resource Include="images\cards\nine of hearts disabled.png" />
    <Resource Include="images\cards\nine of hearts rotated.png" />
    <Resource Include="images\cards\nine of hearts.png" />
    <Resource Include="images\cards\nine of spades disabled.png" />
    <Resource Include="images\cards\nine of spades rotated.png" />
    <Resource Include="images\cards\nine of spades.png" />
    <Resource Include="images\cards\queen of clubs disabled.png" />
    <Resource Include="images\cards\queen of clubs rotated.png" />
    <Resource Include="images\cards\queen of clubs.png" />
    <Resource Include="images\cards\queen of diamonds disabled.png" />
    <Resource Include="images\cards\queen of diamonds rotated.png" />
    <Resource Include="images\cards\queen of diamonds.png" />
    <Resource Include="images\cards\queen of hearts disabled.png" />
    <Resource Include="images\cards\queen of hearts rotated.png" />
    <Resource Include="images\cards\queen of hearts.png" />
    <Resource Include="images\cards\queen of spades disabled.png" />
    <Resource Include="images\cards\queen of spades rotated.png" />
    <Resource Include="images\cards\queen of spades.png" />
    <Resource Include="images\cards\seven of clubs disabled.png" />
    <Resource Include="images\cards\seven of clubs rotated.png" />
    <Resource Include="images\cards\seven of clubs.png" />
    <Resource Include="images\cards\seven of diamonds disabled.png" />
    <Resource Include="images\cards\seven of diamonds rotated.png" />
    <Resource Include="images\cards\seven of diamonds.png" />
    <Resource Include="images\cards\seven of hearts disabled.png" />
    <Resource Include="images\cards\seven of hearts rotated.png" />
    <Resource Include="images\cards\seven of hearts.png" />
    <Resource Include="images\cards\seven of spades disabled.png" />
    <Resource Include="images\cards\seven of spades rotated.png" />
    <Resource Include="images\cards\seven of spades.png" />
    <Resource Include="images\cards\ten of clubs disabled.png" />
    <Resource Include="images\cards\ten of clubs rotated.png" />
    <Resource Include="images\cards\ten of clubs.png" />
    <Resource Include="images\cards\ten of diamonds disabled.png" />
    <Resource Include="images\cards\ten of diamonds rotated.png" />
    <Resource Include="images\cards\ten of diamonds.png" />
    <Resource Include="images\cards\ten of hearts disabled.png" />
    <Resource Include="images\cards\ten of hearts rotated.png" />
    <Resource Include="images\cards\ten of hearts.png" />
    <Resource Include="images\cards\ten of spades disabled.png" />
    <Resource Include="images\cards\ten of spades rotated.png" />
    <Resource Include="images\cards\ten of spades.png" />
    <Resource Include="images\icons\arrow left.png" />
    <Resource Include="images\icons\arrow right.png" />
    <Resource Include="images\icons\black.png" />
    <Resource Include="images\icons\Cards-Play-128.png" />
    <Resource Include="images\icons\Cards-Play-16.png" />
    <Resource Include="images\icons\Cards-Play-32.png" />
    <Resource Include="images\icons\Cards-Play-64.png" />
    <Resource Include="images\icons\dealer.png" />
    <Resource Include="images\icons\Exit-128.png" />
    <Resource Include="images\icons\Exit-16.png" />
    <Resource Include="images\icons\Exit-32.png" />
    <Resource Include="images\icons\Exit-64.png" />
    <Resource Include="images\icons\green.png" />
    <Resource Include="images\icons\Help-128.png" />
    <Resource Include="images\icons\Help-16.png" />
    <Resource Include="images\icons\Help-32.png" />
    <Resource Include="images\icons\Help-64.png" />
    <Resource Include="images\icons\lead card indicator.png" />
    <Resource Include="images\icons\Playing-Cards-128.ico" />
    <Resource Include="images\icons\Playing-Cards-128.png" />
    <Resource Include="images\icons\Playing-Cards-16.ico" />
    <Resource Include="images\icons\Playing-Cards-16.png" />
    <Resource Include="images\icons\Playing-Cards-32.ico" />
    <Resource Include="images\icons\Playing-Cards-32.png" />
    <Resource Include="images\icons\Playing-Cards-64.ico" />
    <Resource Include="images\icons\Playing-Cards-64.png" />
    <Resource Include="images\icons\red.png" />
    <Resource Include="images\icons\Settings-01-128.png" />
    <Resource Include="images\icons\Settings-01-16.png" />
    <Resource Include="images\icons\Settings-01-32.png" />
    <Resource Include="images\icons\Settings-01-64.png" />
    <Resource Include="images\icons\Solo Original.pdn" />
    <Resource Include="images\icons\Solo.ico" />
    <Resource Include="images\icons\Solo.png" />
    <Resource Include="images\icons\trick won indicator.png" />
    <Resource Include="images\suits\Clubs.png" />
    <Resource Include="images\suits\Diamonds.png" />
    <Resource Include="images\suits\Hearts.png" />
    <Resource Include="images\suits\Spades.png" />
  </ItemGroup>

</Project>
