<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.2.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CrazyCanuckCoder.Library.Common">
      <HintPath>..\..\CrazyCanuckCoder\Library.Common\bin\Debug\net8.0-windows\CrazyCanuckCoder.Library.Common.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Data\GameSettingsDS.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GameSettingsDS.xsd</DependentUpon>
    </Compile>
    <Compile Update="Data\GameStateDS.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>GameStateDS.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Data\GameSettings.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Data\GameSettingsDS.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>GameSettingsDS.Designer.cs</LastGenOutput>
    </None>
    <None Update="Data\GameStateDS.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>GameStateDS.Designer.cs</LastGenOutput>
    </None>
    <None Update="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
